SELECT Ssn, SUM(Hours) AS Total_hours FROM EMPLOYEE INNER JOIN WORKS_ON ON Essn = Ssn GROUP BY Ssn;
SELECT Plocation FROM EMPLOYEE INNER JOIN WORKS_ON ON Ssn = Essn INNER JOIN PROJECT ON Pno = Pnumber WHERE Ssn = (SELECT Ssn FROM EMPLOYEE WHERE Fname = 'John');
SELECT Ssn, Fname, Lname, COUNT(*) FROM EMPLOYEE JOIN DEPENDENT ON Ssn = Essn GROUP BY Ssn ORDER BY COUNT(*) ASC;
SELECT Dname, MAX(Salary) AS MAX_SAL FROM EMPLOYEE JOIN DEPARTMENT ON Dno = Dnumber GROUP BY Dno, Dname;
SELECT DISTINCT Ssn, Fname, Lname FROM EMPLOYEE JOIN WORKS_ON ON Ssn = Essn JOIN PROJECT ON Pno = Pnumber WHERE Address LIKE CONCAT('%', Plocation, '%');
